global:
  external_labels:
    monitor: 'Providers-Gateway'

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://www.amazon.com
          - http://www.apache.com
          - http://www.google.com
          - http://www.facebook.com
          - http://www.microsoft.com
          - http://www.oracle.com
          - http://www.yahoo.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.3:9115 # Blackbox exporter
